name: Auto Assign Reviewer

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, ready_for_review]

permissions:
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Assign reviewer
        uses: actions/github-script@v7
        with:
          script: |
            const reviewers = ['Stml89'];
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers
            });
