name: Mypy

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize, ready_for_review]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Analysing the code with mypy
        run: |
          mypy .