name: Pylint

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize, ready_for_review]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          pylint .